//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstorijaKupovine
    {
        public int IDIstorijaKupovine { get; set; }
        public Nullable<int> IDKorisnik { get; set; }
        public Nullable<int> IDPonudaiPoslovniObjekti { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual PonudaiPoslovniObjekti PonudaiPoslovniObjekti { get; set; }
    }
}
