//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KuponiEntities : DbContext
    {
        public KuponiEntities()
            : base("name=KuponiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IstorijaKupovine> IstorijaKupovine { get; set; }
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Obavestenje> Obavestenje { get; set; }
        public virtual DbSet<Ponuda> Ponuda { get; set; }
        public virtual DbSet<PonudaiPoslovniObjekti> PonudaiPoslovniObjekti { get; set; }
        public virtual DbSet<PoslovniObjekti> PoslovniObjekti { get; set; }
        public virtual DbSet<Recenzija> Recenzija { get; set; }
        public virtual DbSet<Rezervacija> Rezervacija { get; set; }
        public virtual DbSet<SlikePonude> SlikePonude { get; set; }
        public virtual DbSet<SlikePoslovnihObjekata> SlikePoslovnihObjekata { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
