//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavestenje
    {
        public int IDObavestenje { get; set; }
        public string Tekst { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> IDKorisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
