//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PonudaiPoslovniObjekti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PonudaiPoslovniObjekti()
        {
            this.IstorijaKupovine = new HashSet<IstorijaKupovine>();
            this.Recenzija = new HashSet<Recenzija>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int IDPonudaiPoslovniObjekti { get; set; }
        public Nullable<int> IDPonuda { get; set; }
        public Nullable<int> IDPoslovniObjekti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstorijaKupovine> IstorijaKupovine { get; set; }
        public virtual Ponuda Ponuda { get; set; }
        public virtual PoslovniObjekti PoslovniObjekti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzija> Recenzija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
