//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ponuda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ponuda()
        {
            this.PonudaiPoslovniObjekti = new HashSet<PonudaiPoslovniObjekti>();
            this.SlikePonude = new HashSet<SlikePonude>();
        }
    
        public int IDPonuda { get; set; }
        public string NazivPonude { get; set; }
        public string OpisPonude { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<double> Cena { get; set; }
        public Nullable<int> IDKategorija { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PonudaiPoslovniObjekti> PonudaiPoslovniObjekti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlikePonude> SlikePonude { get; set; }
    }
}
