//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoslovniObjekti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoslovniObjekti()
        {
            this.PonudaiPoslovniObjekti = new HashSet<PonudaiPoslovniObjekti>();
            this.SlikePoslovnihObjekata = new HashSet<SlikePoslovnihObjekata>();
        }
    
        public int IDPoslovniObjekti { get; set; }
        public string NazivObjekta { get; set; }
        public string Grad { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PonudaiPoslovniObjekti> PonudaiPoslovniObjekti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlikePoslovnihObjekata> SlikePoslovnihObjekata { get; set; }
    }
}
