//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlikePonude
    {
        public int IDSlikaPonude { get; set; }
        public string Putanja { get; set; }
        public Nullable<int> IDPonuda { get; set; }
    
        public virtual Ponuda Ponuda { get; set; }
    }
}
