//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaKuponi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlikePoslovnihObjekata
    {
        public int IDSlikePoslovnihObjekata { get; set; }
        public string Putanja { get; set; }
        public Nullable<int> IDPoslovniObjekti { get; set; }
    
        public virtual PoslovniObjekti PoslovniObjekti { get; set; }
    }
}
